id: P004179
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:41.751052
source_metadata:
  id: bdr:W3CN2385
  title: གསེར་འོད་དམ་པ།
  author: ''
  volumes:
    1be8b39e587741aeac46b5107f396bf0:
      image_group_id: I3CN2387
      title: ''
      volume_number: 1
      total_pages: 567
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
