id: P004179
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2385
  title: གསེར་འོད་དམ་པ།
  author: ''
  volumes:
    1be8b39e587741aeac46b5107f396bf0:
      image_group_id: I3CN2387
      title: ''
      volume_number: 1
      total_pages: 567
      base_file: v001.txt
