id: P004179
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN2385
  title: གསེར་འོད་དམ་པ།
  author: ''
  volumes:
    1be8b39e587741aeac46b5107f396bf0:
      image_group_id: I3CN2387
      title: ''
      volume_number: 1
      total_pages: 567
      base_file: v001.txt
